var emojiLibrary = [
  ["😀", "&#x1F600", "Grinning Face", "1F600"] ,
  ["😬", "&#x1F62C", "Grimacing Face", "1F62C"] ,
  ["😁", "&#x1F601", "Grinning Face with Smiling Eyes (Grimacing?)", "1F601"] ,
  ["😂", "&#x1F602", "Face with Tears of Joy", "1F602"] ,
  ["😃", "&#x1F603", "Smiling Face with Open Mouth", "1F603"] ,
  ["😄", "&#x1F604", "Smiling Face with Open Mouth and Smiling Eyes", "1F604"] ,
  ["😅", "&#x1F605", "Smiling Face with Open Mouth and Cold Sweat", "1F605"] ,
  ["😆", "&#x1F606", "Smiling Face with Open Mouth and Tightly-Closed Eyes", "1F606"] ,
  ["😇", "&#x1F607", "Smiling Face with Halo", "1F607"] ,
  ["😉", "&#x1F609", "Winking Face", "1F609"] ,
  ["😊", "&#x1F60A", "Smiling Face with Smiling Eyes", "1F60A"] ,
  ["🙂", "&#x1F642", "Slightly Smiling Face", "1F642"] ,
  ["🙃", "&#x1F643", "Upside-Down Face", "1F643"],
  ["☺️", "&#x263A", "Smiling Face", "263A/FE0F"],
  ["😋", "&#x1F60B", "Face Savouring Delicious Food", "1F60B"],
  ["😌", "&#x1F60C", "Relieved Face", "1F60C"],
  ["😍", "&#x1F60D", "Smiling Face with Heart-Shaped Eyes", "1F60D"],
  ["😘", "&#x1F618", "Face Throwing a Kiss", "1F618"],
  ["😗", "&#x1F617", "Kissing Face", "1F617"],
  ["😙", "&#x1F619", "Kissing Face with Smiling Eyes", "1F619"],
  ["😚", "&#x1F61A", "Kissing Face with Closed Eyes", "1F61A"],
  ["😜", "&#x1F61C", "Face with Stuck-Out Tongue and Winking Eye", "1F61C"],
  ["😝", "&#x1F61D", "Face with Stuck-Out Tongue and Titghtly-Closed Eyes", "1F61D"],
  ["😛", "&#x1F61B", "Face with Stuck-Out Tongue", "1F61B"],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],
  ["", "&#x", "", ""],

]
